env:
  components:
  - Build:
      build_labor: 10
      payment: 10
      payment_max_skill_multiplier: 3
      skill_dist: pareto
  - ContinuousDoubleAuction:
      max_bid_ask: 10
      max_num_orders: 5
      order_duration: 50
      order_labor: 0.25
  - Gather:
      collect_labor: 1
      move_labor: 1
      skill_dist: pareto
  - PeriodicBracketTax:
      bracket_spacing: us-federal
      disable_taxes: true
      period: 100
      tax_annealing_schedule:
      - -100
      - 0.001
      usd_scaling: 1000
  dense_log_frequency: 20
  energy_cost: 0.21
  energy_warmup_constant: 5000
  energy_warmup_method: auto
  env_layout_file: quadrant_25x25_20each_30clump.txt
  # env_layout_file: no_walls.txt
  episode_length: 1000
  fixed_four_skill_and_loc: true
  flatten_masks: true
  flatten_observations: true
  isoelastic_eta: 0.23
  multi_action_mode_agents: false
  multi_action_mode_planner: true
  n_agents: 4
  planner_gets_spatial_info: false
  planner_reward_type: coin_eq_times_productivity
  scenario_name: nonlinear_disutility
  starting_agent_coin: 0
  world_size:
  - 25
  - 25
general:
  ckpt_frequency_steps: 750000
  cpus: 48
  # episodes: 25000
  episodes: 10000
  gpus: 0
  restore_tf_weights_agents: ''
  restore_tf_weights_planner: ''
  train_planner: false
agent_policy:
  use_critic: true
  use_gae: true
  lambda: 0.98
  grad_clip: 10.0
  lr_schedule: null
  vf_loss_coeff: 0.05
  entropy_coeff: 0.025
  entropy_coeff_schedule: null
  sample_async: true

  gamma: 0.95
  lr: 0.001

  model:
    custom_model: keras_conv_lstm
    custom_options:
      fc_dim: 128
      idx_emb_dim: 4
      input_emb_vocab: 100
      lstm_cell_size: 128
      num_conv: 2
      num_fc: 2
    max_seq_len: 25

planner_policy:
  use_critic: true
  use_gae: true
  lambda: 0.98
  grad_clip: 10.0
  lr_schedule: null
  vf_loss_coeff: 0.05
  entropy_coeff: 0.025
  entropy_coeff_schedule: null
  sample_async: true

  gamma: 0.99
  lr: 0.001

  model:
    custom_model: random
    custom_options: {}
    max_seq_len: 25

trainer:
  batch_mode: truncate_episodes
  env_config: null
  local_tf_session_args:
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 24
  metrics_smoothing_episodes: null
  multiagent: null
  no_done_at_end: false
  num_envs_per_worker: 1
  num_gpus: 0
  num_gpus_per_worker: 0
  num_workers: 32
  observation_filter: NoFilter
  rollout_fragment_length: 200
  seed: null
  tf_session_args:
    allow_soft_placement: true
    device_count:
      CPU: 48
      GPU: 0
    gpu_options:
      allow_growth: true
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 24
    log_device_placement: false
  train_batch_size: 6000
algo: a3c
